print("a\tb\ta**b")
print("{}\t{}\t{}".format(1, 2, 1**2))
print("{}\t{}\t{}".format(2, 3, 2**3))
print("{}\t{}\t{}".format(3, 4, 3**4))
print("{}\t{}\t{}".format(4, 5, 4**5))
print("{}\t{}\t{}".format(5, 6, 5**6))
